### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by Aciho** [rockobonaparte/bfsr#10]
More of a heads up than anything - I've been having severe issues with lag caused by dimension 2 (the tutorial dimension). [I'm talking the the RFTools guy](https://github.com/McJty/RFTools/issues/935) to see if he has any suggestions. I'll let you know if anything interesting comes of it.

**Comment by rockobonaparte** [comment]
I already talked to him about some stuff. One thing I am slated to do is
reduce its power consumption to 0 so I do not need to chunkload a dimension
builder for it. I would have tried it already, but I am dealing with an
uppity new computer that keeps hard crashing.

**Comment by rockobonaparte** [comment]
I don't know how well I can reproduce it over here. The big problem I've had is a huge pile of lag when first starting the game or using the rattle. I think that might be my own teleportation code. It was also creating those nether portals. I thought I fixed that in commit 12854dc356ef2600ec658a09292a64618ade8bc7. Maybe I did and I didn't actually put that build in the pack. Who knows. So I'll be focusing on that personally in the short term.

**Comment by Aciho** [comment]
Can confirm that the nether portal bug is still in the released version, at least when run on a server.

**Comment by rockobonaparte** [comment]
I just fixed the nether bug in code. It should be fixed in the next release. As for lag, it looks like everything I was doing was actually unrelated. I was trying to reduce lag when trying to teleport around. In particular, things would jack right up locally if I used the rattle in the tutorial dimension. I fixed that, but it was its own thing.

The assessments I was doing by outright deleting mods was towards trying to improve things when I did those teleports, so that was all a red herring.

**Comment by rockobonaparte** [comment]
FWIW I think I figured out how to eliminate the chunk loaders on all the dimensions. I sent some thoughts to McJty, but it appears to be working here for me. I had to hack some NBT data to do it, but that will deploy to future versions.

Well, people will have to flatten DIM2 with the one in the latest bfsrworld when I release again.
